file_format: "1"
id: cosmo
name: Cosmo
type: shield
url: https://github.com/foostan/crkbd/
requires: [pro_micro]
exposes: [i2c_oled]
features:
  - keys
  - display
  - underglow
  - studio
siblings:
  - cosmo_left
  - cosmo_right
